[firmware]
; FIP uboot 文件路径
uboot_file = files/immortalwrt-25.12.0-mediatek-filogic-xiaomi_mi-router-ax3000t-ubootmod-bl31-uboot.fip

; sysupgrade .itb 文件路径
sysupgrade_file = files/immortalwrt-mediatek-filogic-xiaomi_mi-router-ax3000t-ubootmod-squashfs-sysupgrade.itb

; overlay tar.gz 路径（可选）
overlay_file = files/overlay-mocktool.tar.gz
